### ISSUE TITLE
Invalid bid order

### ISSUE THREAD

**Issue by fanaticalfishing** [incentivetoken/offspring#15]
Offsping keeps scanning the blockchain

I reports an invalid bid order, then rescans
Here is a screenshot

![screenshot 2014-05-24 14 26 50](https://cloud.githubusercontent.com/assets/7097261/3075588/b534cd48-e382-11e3-8de7-54cd21204b0f.png)

**Comment by incentivetoken** [comment]
Thats almost certainly a NXT problem. Jean-Luc was in fact asking for feedback if this was seen again in the wild. Now it seems you have. 
Not sure what they want with it but you can report NXT issues here https://bitbucket.org/JeanLucPicard/nxt/issues. I can imagine he could use your blockchain to be able to debug this so if you could put that aside (rename the nxt_db folder or something) and let him know you have those files then you could even upload them through their bitbucket page (don't do that right away, he'll let you know if he needs that).

Be sure to mention you are on Offspring 0.4.6 with NXT 1.1.3.

Thanks for reporting this! I'll leave this issue open for a short while.

**Comment by fanaticalfishing** [comment]
OK, will do

**Comment by fanaticalfishing** [comment]
JL told me that this has been resolved in 1.1.4

**Comment by fanaticalfishing** [comment]
I was able to fix it by deleting the blockchain
