### ISSUE TITLE
OS X 10.5.8 Installation docs

### ISSUE THREAD

**Issue by jbshirk** [incentivetoken/offspring#9]
## I am not finding installation docs for Mac. The dependence on Java 6 or 7 could be a problem for Leopard users. This is my log after running offspring:

!SESSION 2014-05-19 10:59:13.300 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.6.0_26
java.vendor=Apple Inc.
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -clearPersistedState -Dosgi.signedcontent.support=authority -keyring /Users/joe/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -clearPersistedState -Dosgi.signedcontent.support=authority -keyring /Users/joe/.eclipse_keyring -showlocation

!ENTRY org.eclipse.equinox.app 0 0 2014-05-19 10:59:24.802
!MESSAGE Product com.dgex.offspring.application.product could not be found.

!ENTRY org.eclipse.osgi 2 0 2014-05-19 10:59:34.391
!MESSAGE One or more bundles are not resolved because the following root constraints are not resolved:
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-05-19 10:59:34.392
!MESSAGE Bundle initial@reference:file:plugins/com.dgex.offspring.ui_1.0.0.201405142041.jar was not resolved.
!SUBENTRY 2 com.dgex.offspring.ui 2 0 2014-05-19 10:59:34.392
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-05-19 10:59:34.392
!MESSAGE Bundle initial@reference:file:plugins/com.dgex.offspring.nxtCore_1.0.0.201405142041.jar was not resolved.
!SUBENTRY 2 com.dgex.offspring.nxtCore 2 0 2014-05-19 10:59:34.392
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-05-19 10:59:34.392
!MESSAGE Bundle initial@reference:file:plugins/org.bouncycastle_1.0.0.201405142041.jar was not resolved.
!SUBENTRY 2 org.bouncycastle 2 0 2014-05-19 10:59:34.392
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".

!ENTRY org.eclipse.osgi 2 0 2014-05-19 10:59:34.460
!MESSAGE The following is a complete list of bundles which are not resolved, see the prior log entry for the root cause if it exists:
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-05-19 10:59:34.460
!MESSAGE Bundle com.dgex.offspring.application_1.0.0.201405142041 [2] was not resolved.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-05-19 10:59:34.460
!MESSAGE Missing required bundle com.dgex.offspring.swt_1.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing required bundle com.dgex.offspring.nxtCore_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package com.dgex.offspring.nxtCore.core_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package com.dgex.offspring.nxtCore.h2_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package com.dgex.offspring.nxtCore.service_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package com.dgex.offspring.providers.bitcoinaverage_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package com.dgex.offspring.providers.dgex_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package com.dgex.offspring.providers.service_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package com.dgex.offspring.providers.utils_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package com.dgex.offspring.trader.api_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package com.dgex.offspring.ui_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package com.dgex.offspring.ui.controls_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package com.dgex.offspring.update_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package com.dgex.offspring.user.service_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package nxt_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package nxt.peer_0.0.0.
!SUBENTRY 2 com.dgex.offspring.application 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package nxt.util_0.0.0.
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-05-19 10:59:34.461
!MESSAGE Bundle com.dgex.offspring.nxtCore_1.0.0.201405142041 [6] was not resolved.
!SUBENTRY 2 com.dgex.offspring.nxtCore 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package nxt_0.0.0.
!SUBENTRY 2 com.dgex.offspring.nxtCore 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package nxt.crypto_0.0.0.
!SUBENTRY 2 com.dgex.offspring.nxtCore 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package nxt.http_0.0.0.
!SUBENTRY 2 com.dgex.offspring.nxtCore 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package nxt.peer_0.0.0.
!SUBENTRY 2 com.dgex.offspring.nxtCore 2 0 2014-05-19 10:59:34.461
!MESSAGE Missing imported package nxt.user_0.0.0.
!SUBENTRY 2 com.dgex.offspring.nxtCore 2 0 2014-05-19 10:59:34.462
!MESSAGE Missing imported package nxt.util_0.0.0.
!SUBENTRY 2 com.dgex.offspring.nxtCore 2 0 2014-05-19 10:59:34.462
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-05-19 10:59:34.462
!MESSAGE Bundle com.dgex.offspring.providers_1.0.0.201405142041 [7] was not resolved.
!SUBENTRY 2 com.dgex.offspring.providers 2 0 2014-05-19 10:59:34.462
!MESSAGE Missing required bundle com.dgex.offspring.nxtCore_1.0.0.
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-05-19 10:59:34.462
!MESSAGE Bundle com.dgex.offspring.swt_1.0.0.201405142041 [8] was not resolved.
!SUBENTRY 2 com.dgex.offspring.swt 2 0 2014-05-19 10:59:34.462
!MESSAGE Missing imported package com.dgex.offspring.nxtCore.service_0.0.0.
!SUBENTRY 2 com.dgex.offspring.swt 2 0 2014-05-19 10:59:34.462
!MESSAGE Missing imported package com.dgex.offspring.swt.table_0.0.0.
!SUBENTRY 2 com.dgex.offspring.swt 2 0 2014-05-19 10:59:34.462
!MESSAGE Missing imported package com.dgex.offspring.user.service_0.0.0.
!SUBENTRY 2 com.dgex.offspring.swt 2 0 2014-05-19 10:59:34.462
!MESSAGE Missing imported package nxt.util_0.0.0.
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-05-19 10:59:34.462
!MESSAGE Bundle com.dgex.offspring.trader_1.0.0.201405142041 [9] was not resolved.
!SUBENTRY 2 com.dgex.offspring.trader 2 0 2014-05-19 10:59:34.462
!MESSAGE Missing required bundle com.dgex.offspring.swt_1.0.0.
!SUBENTRY 2 com.dgex.offspring.trader 2 0 2014-05-19 10:59:34.462
!MESSAGE Missing required bundle com.dgex.offspring.nxtCore_0.0.0.
!SUBENTRY 2 com.dgex.offspring.trader 2 0 2014-05-19 10:59:34.462
!MESSAGE Missing imported package com.dgex.offspring.nxtCore.core_0.0.0.
!SUBENTRY 2 com.dgex.offspring.trader 2 0 2014-05-19 10:59:34.462
!MESSAGE Missing imported package com.dgex.offspring.nxtCore.service_0.0.0.
!SUBENTRY 2 com.dgex.offspring.trader 2 0 2014-05-19 10:59:34.462
!MESSAGE Missing imported package com.dgex.offspring.providers.utils_0.0.0.
!SUBENTRY 2 com.dgex.offspring.trader 2 0 2014-05-19 10:59:34.462
!MESSAGE Missing imported package com.dgex.offspring.ui_0.0.0.
!SUBENTRY 2 com.dgex.offspring.trader 2 0 2014-05-19 10:59:34.462
!MESSAGE Missing imported package com.dgex.offspring.user.service_0.0.0.
!SUBENTRY 2 com.dgex.offspring.trader 2 0 2014-05-19 10:59:34.462
!MESSAGE Missing imported package nxt_0.0.0.
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-05-19 10:59:34.462
!MESSAGE Bundle com.dgex.offspring.ui_1.0.0.201405142041 [10] was not resolved.
!SUBENTRY 2 com.dgex.offspring.ui 2 0 2014-05-19 10:59:34.462
!MESSAGE Missing required bundle com.dgex.offspring.nxtCore_0.0.0.
!SUBENTRY 2 com.dgex.offspring.ui 2 0 2014-05-19 10:59:34.462
!MESSAGE Missing required bundle org.bouncycastle_1.0.0.
!SUBENTRY 2 com.dgex.offspring.ui 2 0 2014-05-19 10:59:34.463
!MESSAGE Missing imported package com.dgex.offspring.swt.table_0.0.0.
!SUBENTRY 2 com.dgex.offspring.ui 2 0 2014-05-19 10:59:34.463
!MESSAGE Missing imported package com.dgex.offspring.swt.wizard_0.0.0.
!SUBENTRY 2 com.dgex.offspring.ui 2 0 2014-05-19 10:59:34.463
!MESSAGE Missing imported package com.dgex.offspring.user.service_0.0.0.
!SUBENTRY 2 com.dgex.offspring.ui 2 0 2014-05-19 10:59:34.463
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-05-19 10:59:34.463
!MESSAGE Bundle com.dgex.offspring.update_1.0.0.201405142041 [11] was not resolved.
!SUBENTRY 2 com.dgex.offspring.update 2 0 2014-05-19 10:59:34.463
!MESSAGE Missing imported package com.dgex.offspring.nxtCore.service_0.0.0.
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-05-19 10:59:34.463
!MESSAGE Bundle com.dgex.offspring.user_1.0.0.201405142041 [12] was not resolved.
!SUBENTRY 2 com.dgex.offspring.user 2 0 2014-05-19 10:59:34.463
!MESSAGE Missing required bundle com.dgex.offspring.nxtCore_1.0.0.
!SUBENTRY 2 com.dgex.offspring.user 2 0 2014-05-19 10:59:34.463
!MESSAGE Missing required bundle com.dgex.offspring.nxtCore_0.0.0.
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-05-19 10:59:34.463
!MESSAGE Bundle org.bouncycastle_1.0.0.201405142041 [30] was not resolved.
!SUBENTRY 2 org.bouncycastle 2 0 2014-05-19 10:59:34.463
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".

!ENTRY org.eclipse.osgi 4 0 2014-05-19 10:59:34.492
!MESSAGE Application error
!STACK 1
org.eclipse.core.runtime.AssertionFailedException: null argument:applicationXMI argument missing
    at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:85)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.loadApplicationModel(E4Application.java:342)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:238)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:144)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)

**Comment by incentivetoken** [comment]
Thats definitely a Java 6 problem (you need 7).  We cannot use 6 since NXT itself requires Java 7.
Other people have run into this same problem, a solution can be found on our old bitbucket account.
https://bitbucket.org/incentivetoken/offspring-public/issue/2/unable-to-run-on-mac-32-bit

Good luck!

**Comment by jbshirk** [comment]
Java 7 cannot be installed on 10.5.8 (to my knowledge) - upgrading to OS X 10.6 entails a chain of problems I am simply not able to deal with yet - need new DVD/RW, backup system and data, delete main partition... etc, etc. 
:(

**Comment by jbshirk** [comment]
Java 7 cannot be installed on 10.5.8 (to my knowledge) - upgrading to OS X
10.6 entails a chain of problems I am simply not able to deal with yet -
need new DVD/RW, backup system and data, delete main partition... etc, etc.
:(

**Comment by incentivetoken** [comment]
Sorry to hear that. Offspring could (and did) run on Java 6 but since NXT requires a lot of Java 7 only features we're stuck with that. Your problem would occur for everyone on your platform and none of them could run NXT (not even through the default client).
All I can advise is to make yourself heard on one of the forums. http://nextcoin.org or http://nxtforum.org and ask for Java 6 support. Best chance of reaching the core dev of NXT is on http://nxtforum.org. To get support for NXT simply open a topic in https://nxtforum.org/nxt-helpdesk/.
